courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.courseInfo, name='course'),
    path('<int:course_id>/enroll', views.enroll, name='enroll'),
    path('<int:course_id>/cancel', views.enrollCancel, name='cancel'),
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path

from . import views 

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('courses', views.indexCourse, name='courses'),
]

courses/models.py
from django.db import models
import datetime

class Course(models.Model):
    SEMESTER = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3/Summer'),
    ]
    
    QUOTA = [
        ('OPEN', 'OPEN'),
        ('CLOSED', 'CLOSED'),
    ]

    course_code = models.CharField(max_length=5)
    course_name = models.CharField(max_length=64)
    semester = models.CharField(max_length=1, default=1, choices=SEMESTER) 
    year = models.IntegerField(default=datetime.datetime.now().year)
    seat = models.PositiveIntegerField(default=99)
    quota = models.CharField(max_length=64, default='OPEN', choices=QUOTA)
    
    def __str__(self):
        return f"{self.course_code} | {self.course_name}"
    
    def is_seat_available(self):
        return self.enrolments.count() < self.seat
    
    def is_quota_available(self):
        return self.quota == "OPEN"

class Enrolment(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    courses = models.ManyToManyField(Course, blank=True, related_name='enrolments')
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

users/models.py
from django.db import models

# Create your models here.

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Course, Enrolment

# Create your views here.

def index(request):
    courses = Course.objects.all()
    return render(request, 'courses/index.html', {
        'courses': courses
    })

def courseInfo(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'courses/course.html', {
        'course': course,
        'enrolments': course.enrolments.all(),
        'nonenrolments': Enrolment.objects.exclude(courses=course).all(),
    })

def enroll(request, course_id):
    if request.method == "POST":
        course = get_object_or_404(Course, pk=course_id)
        enrolment = get_object_or_404(Enrolment, pk=int(request.POST['enrolment']))
        if enrolment not in course.enrolments.all() and course.is_seat_available():
            enrolment = Enrolment.objects.get(pk=int(request.POST["enrolment"]))
            enrolment.courses.add(course)
        return HttpResponseRedirect(reverse('courses:course', args=(course_id,)))
    
def enrollCancel(request, course_id):
     if request.method == "POST":
        course = get_object_or_404(Course, pk=course_id)
        enrolment = get_object_or_404(Enrolment, pk=int(request.POST['enrolment']))
        if enrolment in course.enrolments.all():
            enrolment = Enrolment.objects.get(pk=int(request.POST["enrolment"]))
            enrolment.courses.remove(course)
        return HttpResponseRedirect(reverse('courses:course', args=(course_id,)))
    

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from courses.models import Course

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    return render(request, 'users/index.html')

def indexCourse(request):
    courses = Course.objects.all()
    return render(request, 'courses/index.html', {
        'courses': courses
    })

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, 'users/login.html', {
                'message': 'Invalid credentials.'
            })
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'You are logged out.'
    })

courses/templates/courses/course.html
{% extends 'courses/layout.html' %}
{% block body %}
<h1>{{ course.course_code }} | {{ course.course_name }}</h1>
<ul>
    <li>Semester: {{ course.semester }}/{{ course.year }}</li>
    <li>Seat: {{ course.seat }}</li>
</ul>

<h2>Registrants</h2>
<ul>
    {% for enrolment in enrolments %}
    <li>{{ enrolment }}</li>
    {% empty %}
    <li>No registrants.</li>
    {% endfor %}
</ul>

<h2>Add Quota</h2>
{% if course.enrolments.count != course.seat and course.quota == 'OPEN' %}
<form action="{% url 'courses:enroll' course.id %}" method="post">
    {% csrf_token %} 
    <select name="enrolment">
        {% for enrolment in nonenrolments %}
        <option value="{{ enrolment.id }}">{{ enrolment }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Add Quota">
</form>
{% elif course.enrolments.count != course.seat and course.quota == 'CLOSED' %}
<p style="color:red">QUOTA IS CLOSED</p>
{% else %}
<p style="color:red">QUOTA IS FULL</p>
{% endif %}

<form action="{% url 'courses:cancel' course.id %}" method="post">
    {% csrf_token %} 
    <select name="enrolment">
        {% for enrolment in enrolments %}
        <option value="{{ enrolment.id }}">{{ enrolment }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Cancel Quota">
</form>

<a href="{% url 'courses:index' %}">Go Back</a>
{% endblock %}

courses/templates/courses/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Courses</title>
    </head>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        } 
        th, td {
            text-align: left;
            padding: 1px;
        }    
        tr:nth-child(even) {
            background-color: #D6EEEE;
        }
    </style>
<body>

<h1>Courses</h1>
<table style="width:35%">
    <tr>
        <th style="width:15%", align=Left>Code</th>
        <th>Course Name</th>
        <th>Seat</th>
        <th><center>Quota status<center></th>
    </tr>
    {% for course in courses %}
    <tr>
        <td>{{ course.course_code }}</td>
        <td>{{ course.course_name }}</td>
        <td>{{ course.enrolments.count }}/{{ course.seat }}</td>
        <td>
            <center>
            {% if course.enrolments.count != course.seat and course.quota == 'OPEN' %}
            <p style="color:green">{{ course.quota }}</p>
            {% elif course.enrolments.count != course.seat and course.quota == 'CLOSED' %}
            <p style="color:red">CLOSED</p>
            {% else %}
            <p style="color:red">FULL</p>
            {% endif %}
            </center>
        <td>
        <td><a href="{% url 'courses:course' course.id %}">Detail</a></td>
    </tr>
    {% empty %}
    <li>No courses.</li>
    {% endfor %}
</table>

<a href="{% url 'users:index' %}">Go Back</a>
</body>
</html>

courses/templates/courses/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Courses</title>
    </head>
    <body> 
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/index.html
{% extends 'users/layout.html' %}
{% block body %}

<h1>Welcome, {{ request.user.first_name }} </h1>
<ul>
    <li>Username: {{ request.user.username }}</li>
    <li>Name: {{ request.user.first_name }} {{ request.user.last_name }}</li>
    <li>Email: {{ request.user.email }}</li>
</ul>

<h2><a href="{% url 'users:courses' %}">Courses</a></h2><br><br>
<a href="{% url 'users:logout' %}">Log out</a>
{% endblock %}

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Users</title>
    </head>
    <body> 
        {% block body %}
        {% endblock %}
    </body>
</html>

users/templates/users/login.html
{% extends 'users/layout.html' %}
{% block body %}

<h1>Login</h1>
{% if message %}
    <div style="color:red">{{ message }}</div>
{% endif %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %} 
    <label>Username</label>
    <input type="text" name="username" placeholder="Username"><br>
    <label>Password</label>
    <input type="password" name="password" placeholder="Password"><br>
    <input type="submit" value="Login">
</form>
{% endblock %}